[package]
name = "selenium-manager"
version = "1.0.0-M2"
edition = "2021"
authors = ["Selenium <selenium-developers@googlegroups.com"]
license = "Apache-2.0"
homepage = "https://www.selenium.dev/"
repository = "https://github.com/SeleniumHQ/selenium"
documentation = "https://www.selenium.dev/documentation/"
description = """
Selenium Manager is a CLI tool that automatically manages the browser/driver infrastructure required by Selenium.
"""

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
log = "0.4.17"
env_logger = "0.10.0"
regex = "1.7.0"
tokio = { version = "1.24.1", default-features = false, features = ["macros", "net", "rt-multi-thread"] }
tempfile = "3.3.0"
reqwest = { version = "0.11.13", default-features = false, features = [ "rustls-tls" ] }
zip = "0.6.3"
directories = "4.0.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
flate2 = "1.0.25"
tar = "0.4.38"
infer = "0.12.0"
exitcode = "1.1.2"

[dev-dependencies]
assert_cmd = "2.0.7"
rstest = "0.16.0"

[profile.release]
opt-level = 'z'     # Optimize for size
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations
panic = 'abort'     # Abort on panic
strip = true        # Strip symbols from binary*
